import type { NextPageContext } from 'next';
import Head from 'next/head';
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';
import Box from '@mui/material/Box';

import {
	Carousel,
	Navbar,
	Paper,
	Footer,
	InfoTitle,
	ProductSlide,
	ProductInfo,
} from '../../components';
import { fetchAPI, getStrapiMedia } from '../../lib/api';
import { ProductResponse } from '../../lib/apiResponse';

import sofaBg from '../../media/banner/sofa.jpeg';

const ProductPage = ({ product }: ProductResponse) => {
	console.log(product);
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<Navbar />

				<Paper img={sofaBg} element={<InfoTitle text={'chargefy'} />} />

				<Container>
					<Box sx={{ my: '5rem' }}>
						<Grid container spacing={4}>
							<Grid item container xs={6} alignItems={'center'}>
								<Carousel
									Slide={ProductSlide}
									content={product.images}
								/>
							</Grid>
							<Grid item xs={6}>
								<ProductInfo {...product} />
							</Grid>
						</Grid>
					</Box>
				</Container>
			</main>

			<Footer />
		</div>
	);
};

ProductPage.getInitialProps = async(ctx: NextPageContext) => {
	const id = ctx.query.id;
	const url = `/products/${id}?populate=*`;
	const response = await fetchAPI(url);
	const product = response.data.attributes;
	const images = product.images.data;

	return {
		product: {
			id: product.id,
			title: product.title,
			description: product.description,
			price: product.price,
			sale: product.sale,
			characteristic: product.characteristic,
			images: images.map((image: any) => {
				const img = image.attributes.formats.medium;
				return {
					url: getStrapiMedia(img.url),
					width: img.width,
					height: img.height,
				}
			})
		}
	} as ProductResponse;
}

export default ProductPage;
