import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Container from '@mui/material/Container';
import Typography from '@mui/material/Typography';
import Grid from '@mui/material/Grid';
import Box from '@mui/material/Box';

import {
  Carousel,
  Navbar,
  Paper,
  Info,
  Products,
  Title,
  Footer,
  InfoTitle,
  ProductSlide,
} from '../../components';

import sofaBg from '../../media/banner/sofa.jpeg';
import logo from '../../media/logo.png';

import img1 from '../../media/carousel/1.png';
import img2 from '../../media/carousel/2.png';
import img3 from '../../media/carousel/3.png';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />

        <Paper img={sofaBg} element={
          <InfoTitle text={'chargefy'} />
        }/>

        <Container>
          <Box sx={{ my: '5rem' }}>
            <Grid container spacing={4}>
              <Grid item container xs={4} alignItems={'center'}>
                <Carousel
                  Slide={ProductSlide}
                  content={[
                    {
                      src: img1,
                    },
                    {
                      src: img2,
                    },
                    {
                      src: img3,
                    },
                  ]}
                />
              </Grid>
              <Grid item xs={8}>

              </Grid>
            </Grid>
          </Box>
        </Container>
      </main>

      <Footer />
    </div>
  )
}

export default Home
