import { useState } from 'react';
import Head from 'next/head';
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';

import { Navbar, Footer, Paper, InfoTitle, Title, ActionButton } from '../../components';

import sofaBg from '../../media/banner/sofa.jpeg';
import OrderForm, { NovaPoschtaInfo, OrderFormValue } from '../../components/OrderForm';
import { fetchNovaPoschtaApi } from '../../lib/api';

const OrderPage = ({ areas }: { areas: Array<NovaPoschtaInfo> }) => {
	const [order, setOrder] = useState<OrderFormValue>({
		name: null,
		surname: null,
		middleName:  null,
		phoneNumber:  null,
		payment: null,
		area: null,
		city: null,
		warehouse: null,
	});

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<Navbar />

				<Paper img={sofaBg} element={<InfoTitle text={'order'} />} />

				<Box sx={{ my: '5rem' }}>
					<Container>
						<Title text={'Order info'} />

						<OrderForm areas={areas} order={order} setOrder={setOrder} />

						<Box sx={{ mt: '4rem' }}>
							<Grid container>
								<Grid item xs={2}></Grid>
								<Grid item xs={8}>
									<ActionButton disabled={Object.values(order).some(value => !value)}>
										замовити
									</ActionButton>
								</Grid>
							</Grid>
						</Box>
					</Container>
				</Box>
			</main>
			<Footer />
		</>
	);
};

OrderPage.getInitialProps = async () => {
	const response = await fetchNovaPoschtaApi({
		modelName: 'Address',
		calledMethod: 'getAreas',
		methodProperties: {},
	});

	return {
		areas: response.data.map((area: any) => ({
			ref: area.Ref,
			name: area.Description,
		})),
	};
};

export default OrderPage;
