import type { NextPage } from 'next';
import Head from 'next/head';
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import Typography from '@mui/material/Typography';

import {
  Carousel,
  Navbar,
  Paper,
  Info,
  Products,
  Title,
  Footer,
  InfoTitle,
} from '../components';

import sofaBg from '../media/banner/sofa.jpeg';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />

        <Paper img={sofaBg} element={
          <InfoTitle text={'about'} />
        }/>
      </main>

      <Footer />
    </div>
  )
}

export default Home
