import type { NextPage } from 'next';
import Head from 'next/head';

import Carousel from '../components/Carousel';
import Navbar from '../components/Navbar';
import Paper from '../components/Paper';
import Info from '../components/Info';

import img1 from '../media/carousel/1.png';
import img2 from '../media/carousel/2.png';
import img3 from '../media/carousel/3.png';

import sofaBg from '../media/banner/sofa.jpeg';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />

        <Carousel content={[
          {
            title: 'Lorem ipsum dolor sit amet',
            description: 'Lacus sed viverra tellus in hac habitasse. Sem nulla pharetra diam sit. Enim diam vulputate ut pharetra sit amet aliquam id. Scelerisque in dictum non consectetur a erat nam. ',
            img: img1,
          },
          {
            title: 'Excepteur sint occaecat cupidatat',
            description: 'Viverra nam libero justo laoreet sit amet cursus. Tincidunt vitae semper quis lectus nulla at volutpat diam. Nulla aliquet enim tortor at. Aliquet enim tortor at auctor urna nunc id cursus.',
            img: img2,
          },
          {
            title: 'Vulputate odio ut enim blandit volutpat',
            description: 'Non consectetur a erat nam. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Ante metus dictum at tempor.',
            img: img3,
          },
        ]} />

        <Paper img={sofaBg} textElement={
          <Info
            title={'Lorem ipsum dolor'}
            description={'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa laboriosam laborum laudantium nam quam ullam unde! Ad autem reiciendis tempora. Aut ex impedit laudantium voluptate?'}
            price={249}
            link={'/'}
          />
        }/>
      </main>

      <footer>

      </footer>
    </div>
  )
}

export default Home
