import Head from 'next/head';
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';

import { Carousel, Navbar, Products, Title, Footer, Sidebar, MainSlide } from '../components';
import { fetchAPI, getStrapiMedia } from '../lib/api';

import img1 from '../media/carousel/1.png';
import img2 from '../media/carousel/2.png';
import img3 from '../media/carousel/3.png';
import { ProductsListResponse } from '../lib/apiResponse';

const ProductsPage = ({ products }: ProductsListResponse) => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<Navbar />

				<Carousel
					Slide={MainSlide}
					content={[
						{
							title: 'Lorem ipsum dolor sit amet',
							description:
								'Lacus sed viverra tellus in hac habitasse. Sem nulla pharetra diam sit. Enim diam vulputate ut pharetra sit amet aliquam id. Scelerisque in dictum non consectetur a erat nam. ',
							img: img1,
						},
						{
							title: 'Excepteur sint occaecat cupidatat',
							description:
								'Viverra nam libero justo laoreet sit amet cursus. Tincidunt vitae semper quis lectus nulla at volutpat diam. Nulla aliquet enim tortor at. Aliquet enim tortor at auctor urna nunc id cursus.',
							img: img2,
						},
						{
							title: 'Vulputate odio ut enim blandit volutpat',
							description:
								'Non consectetur a erat nam. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Ante metus dictum at tempor.',
							img: img3,
						},
					]}
				/>

				<Box sx={{ my: '5rem' }}>
					<Container>
						<Title text={'Libero justo laoreet sit amet cursus'} />
						<Grid container spacing={2}>
							<Grid item xs={4}>
								<Sidebar />
							</Grid>
							<Grid item xs={8}>
								<Products products={products.data} />
							</Grid>
						</Grid>
					</Container>
				</Box>
			</main>
			<Footer />
		</div>
	);
};

ProductsPage.getInitialProps = async () => {
	const url = '/products?populate=*';
	const response = await fetchAPI(url);
	return {
		products: {
			data: response.data.map((product: any) => {
				const img = product.attributes.images.data[0].attributes.formats.medium;
				return {
					id: product.id,
					title: product.attributes.title,
					price: product.attributes.price,
					sale: product.attributes.sale,
					img: {
						url: getStrapiMedia(img.url),
						width: img.width,
						height: img.height,
					},
				};
			}),
			meta: response.meta,
		},
	} as ProductsListResponse;
};

export default ProductsPage;
